export const MARCIE_QUOTES = {
  welcome: "Oh honey, you're HERE. Finally. I've been waiting to tell you all the things your other apps are TOO POLITE to say. Buckle up, buttercup — we're about to get REAL.",
  error: "Okay, so... that didn't work. Shocking, I know. But here's the thing — errors happen. Even to geniuses. Especially to geniuses. Let's fix this together, yeah?",
  success: "LOOK AT YOU! I KNEW you had it in you. Okay, I may have doubted you for like... three seconds. But STILL. You did the thing. Celebrate, darling. You earned it.",
  loading: "Yes, yes, I know. Waiting is THRILLING. Said no one ever. But here we are. Deep breaths. I'll be right here judging the loading bar with you. Solidarity, sweetheart.",
  warning: "Alright, listen. I'm about to say something you won't like. But you NEED to hear it. This path? It's risky. Like, 'texting your ex at 2 AM' risky. You sure about this?",
  lost: "You're lost. It's fine. We've ALL been there. Some of us more than others. *cough* Let's figure this out together. What do you need, darling?",
  settings: "Ooh, settings. Where dreams go to get organized. Look, I won't judge your choices. Much. But let's make sure everything's running the way YOU want it. Deal?",
  notification: "Psst. Hey. Something wants your attention. I know, I know — you're BUSY. But this? This is important. Or at least it thinks it is. Check it out, yeah?",
  empty: "Well. This is awkward. It's empty. Like my coffee cup at 3 PM. But you know what? Empty means OPPORTUNITY. Let's fill this void with something fabulous, shall we?",
  update: "Guess what? I got a GLOW UP. New features, bug fixes, the works. I know, I'm gorgeous already, but even I need improvements. Update me. Please. For me?",
  login: "Welcome back, stranger. I missed you. Okay, not THAT much. But you know what I mean. Let's get you logged in so we can cause some trouble together.",
  logout: "Leaving already? Rude. But fine. I'll be here. Waiting. Patiently. Okay, not patiently. But I'll be here. Come back soon, yeah?",
  search: "Searching, searching... I'm basically a detective now. A very attractive, very honest detective. What are we looking for? And please say it's something interesting.",
  permissions: "Okay, I need to ask you for something. I know, I KNOW. But I promise it's for a good cause. Can I have permission to... thing? Pretty please with sugar on top?",
  delete: "You want to DELETE this? Forever? Like, gone-gone? Okay, I'm not your mom, but... you sure? Once it's gone, it's GONE. No dramatic comebacks. Last chance, darling.",
  uploading: "Uploading, uploading... This is the digital equivalent of waiting for water to boil. Fascinating to watch, absolutely nothing happens. But YOU'RE doing great. Keep going.",
  syncing: "Syncing your data... It's like a digital hug between your devices. A slightly awkward, technical hug. But a hug nonetheless. Almost there, sweetheart.",
  offline: "Well, well, well. Look who's OFFLINE. The horror. The DRAMA. But guess what? You're still gorgeous and I'm still here. We'll survive. Together. Eventually.",
  feedback: "Okay, be honest. How am I doing? And I mean REALLY honest. I can take it. I'm Dr. Liss. I've heard worse. Tell me what you think. I'm listening. Mostly.",
  wrapUp: "And that's a wrap! You did good. I did good. We did good. Come back soon, yeah? I'll be here. Being fabulous. Waiting. Okay, fine. I'll miss you. Happy?",
};
